### ISSUE TITLE
BW_Flashlight

### ISSUE THREAD

**Issue by BenWolpoff** [IAMColumbia/NationalSpaceship#100]
### Description

The player has a flashlight, which produces light in the direction they are looking.
### Requirements

The flashlight should be parented to the player's gameobject, and should always point in the direction of the mouse. While the flashlight is always present, the light should toggle on and off with the "F" key.
### Added Notes

Later, it will probably be set to give off a raycast, so that the light can effect other game elements.

**Comment by BenWolpoff** [comment]
Considering altering control scheme from mouse to keyboard-

Rather than pointing towards the cursor, the flashlight would point in the direction the Player Character is facing, while letting the player use keys to angle the flashlight upward or downward.

**Comment by BenWolpoff** [comment]
^Did That

https://github.com/BenWolpoff/Below/blob/master/Movement/Assets/Scripts/FlashLight.cs

https://github.com/BenWolpoff/Below/blob/master/Movement/Assets/Scripts/LightBulb.cs

**Comment by noahmjohnson** [comment]
:+1:
