### ISSUE TITLE
TF_Magic Spells

### ISSUE THREAD

**Issue by Gamewiz21** [IAMColumbia/NationalSpaceship#109]
Description
The player will be able to use magic as an additional attacking method. At a certain point in the game the player will open a spell book and be able to use magic abilities such as “Fireball”. There will be no magic value so the player can use it as much as he wants and some obstacles and enemies can only be defeated by magic

Requirements
• Player will be able launch magic at enemies on button press
• Magic will be instantiated from the player and damage enemies
• Some spells will be more effective on certain enemies
• Magic will be able to destroy certain objects in the scene 

Added Note
There may be 1-3 spells usable in the final game.

**Comment by noahmjohnson** [comment]
Are you stil implementing this?

**Comment by Gamewiz21** [comment]
Yes

**Comment by Gamewiz21** [comment]
Fireball Shooter:
https://github.com/Gamewiz21/TF_GAIA/blob/master/AESGame/Assets/MyScripts/Fireballshoot.cs
Sound:
https://github.com/Gamewiz21/TF_GAIA/blob/master/AESGame/Assets/MyScriptslvl2/FireballSfx.cs:
