### ISSUE TITLE
LL_Jump

### ISSUE THREAD

**Issue by MasqureMan** [IAMColumbia/NationalSpaceship#111]
Description: Player will be able to jump in order to navigate the game environment vertically and navigate around obstacles and enemies. 

Requirements: 
Control input for jumping.
IsGrounded/IsAerial checks to see if the character is able to jump and how fast they can move while aerial. 
Physics.
Landing.

**Comment by noahmjohnson** [comment]
Where is the code attached for this issue?

**Comment by MasqureMan** [comment]
Jump code is in the Character Control script. Checks in Update if the player is grounded and the space button is being pressed.

https://github.com/MasqureMan/PlagueMaster/blob/master/PlatformPractice/Assets/Scripts/CharacterControl.cs
