### ISSUE TITLE
LL_Attack

### ISSUE THREAD

**Issue by MasqureMan** [IAMColumbia/NationalSpaceship#113]
Description: The player will swing their weapon, dealing damage to what’s in front of them. In the future, this will be tied to flinching when hitting weaker enemies and building energy in the plague meter. 
 Requirements: 
• Input: player presses the attack button
• The attack will hit all enemies in range of it. It is not limited to hitting a single enemy.
• System may listen for “attack” to fire.
• An animation will be required to display the attack and need to be timed correctly to match the speed of the attack’s impact.

**Comment by noahmjohnson** [comment]
Where is the code attached for this issue?
