### ISSUE TITLE
LL_PlagueBolt

### ISSUE THREAD

**Issue by MasqureMan** [IAMColumbia/NationalSpaceship#115]
Description: The player spends a specified amount of energy stored in the Plague Meter to fire a projectile called a Plague Bolt, which does more damage than a normal attack when it hits an enemy. In the future, this may slow enemy movement as well. 

Requirements: 
• Input: player presses bolt button with the required amount of plague energy stored.
• Plague Meter and method of storing energy must be implemented.
• Projectile will be destroyed around the time it exits the screen and as it collides with enemies.

**Comment by noahmjohnson** [comment]
Where is the code attached for this issue?

**Comment by MasqureMan** [comment]
https://github.com/MasqureMan/PlagueMaster/blob/master/PlatformPractice/Assets/Scripts/PlagueBolt.cs

**Comment by MasqureMan** [comment]
Plague Bolts are now properly destroyed when they collide with turret projectiles and turrets. 

https://github.com/MasqureMan/PlagueMaster/blob/master/PlatformPractice/Assets/Scripts/BoltHP.cs
