### ISSUE TITLE
LL_PlagueMeter

### ISSUE THREAD

**Issue by MasqureMan** [IAMColumbia/NationalSpaceship#116]
Description: A green Plague Meter will be in one of the corners of the screen and will serve as a gauge for the amount of energy the player has stored. Upon attacking enemies, they will build this energy up to a maximum. A certain amount is needed to fire a plague bolt and that amount will decrease from the plague meter. It will look like a vial or empty container that is being filled up.

Requirements: 
• The plague meter will need to have a visual representation in the user interface. 
• The meter will need to interact with the “attack” script and the “plague bolt” script in order to add and remove energy to and from the meter.

**Comment by noahmjohnson** [comment]
Where is the code attached for this issue?
