### ISSUE TITLE
LL_Flinching

### ISSUE THREAD

**Issue by MasqureMan** [IAMColumbia/NationalSpaceship#117]
Description: When an enemy classified as "weak" is hit by a player attack, they will flinch. Enemies classified as "strong" will not flinch. This will interrupt their current movement and attack, giving the player an opening to deal more damage. A delay may be implemented between flinching triggers depending on testing. 

Requirements:
• Enemies must be labeled as weak or strong.
• Attacking must be implemented. 
• Attacks must check for enemy tags of weak or strong upon connecting with an enemy.
• A way to properly stop an enemies “attack” animation and transition into a “flinching” animation must be implemented.

**Comment by noahmjohnson** [comment]
Where is the code attached for this issue?

**Comment by MasqureMan** [comment]
Didn't end up implementing flinching as a mechanic
