### ISSUE TITLE
CM_CameraMovement

### ISSUE THREAD

**Issue by coryMedrano1** [IAMColumbia/NationalSpaceship#130]
### Description

Camera Control.
### Requirements

Camera should follow the player.
#### New Code

https://github.com/coryMedrano1/EcoTGM/blob/master/Eco/Assets/scripts/cameraScript.cs
### Previous Work

None

**Comment by coryMedrano1** [comment]
New Code: https://github.com/coryMedrano1/EcoTGM/blob/master/Eco/Assets/scripts/cameraScript.cs

**Comment by noahmjohnson** [comment]
:+1:
