### ISSUE TITLE
SB_FirstLevel/FirstEncounter

### ISSUE THREAD

**Issue by TBGDeathPunch** [IAMColumbia/NationalSpaceship#137]
Description:
For my first encounter level I plan to have the player have to deal with getting around the first introduction to the guards. If the player's character goes into the vision of the guard the level will be reset after a short delay. I hope to have the guard catch working and the level reset working along with the player's single movement type. I will also have a level reset at the end of the level so that it can be replayed.

Requirements:
The level will bring in all of the basic mechanics and work to be easy and a stepping stone level for the later levels.

**Comment by noahmjohnson** [comment]
Please format this issue correctly. Refer to the requirements pages .
