### ISSUE TITLE
SC_MovingPlatforms

### ISSUE THREAD

**Issue by JbrockPony** [IAMColumbia/NationalSpaceship#139]
## Issue Requirement Breakdown

I need help in implementing moving platforms. 
### Description

I'm making a simple 2D platformer. The character will just keep jumping onto platforms till he/she reaches the goal. However, I'm using a combination of 2D sprites and cubes as platforms with box colliders. My character does not detect the colliders on the cubes. 
#### New Code
- Using the standard unit assets for 2D character controller. 
### Previous Work
- Added sprites
### Other Notes

https://github.com/JbrockPony/2D-Platformer-V1

**Comment by noahmjohnson** [comment]
Please see my comments in #152
