### ISSUE TITLE
SC_Jumping

### ISSUE THREAD

**Issue by JbrockPony** [IAMColumbia/NationalSpaceship#151]
## Issue Requirement Breakdown

Infinite jumping. Cool but not what I had in mind. 
### Description

My player was infinitely jumping. 
#### New Code

https://github.com/JbrockPony/2D-Platformer-V1/blob/master/Assets/Standard%20Assets/2D/Scripts/PlatformerCharacter2D.cs 
### Previous Work
- Added sprites
### Other Notes

The problem could be the player is dectecting itself as being grounded. 
https://github.com/JbrockPony/2D-Platformer-V1

**Comment by JbrockPony** [comment]
Removed detection of player colliding with self while in air.

**Comment by noahmjohnson** [comment]
@JbrockPony I think you need to make sure your repo is public and not private. The link does not work for me. Unless you include me as a user on your repo. If you add me, I can check it out.
