### ISSUE TITLE
SC_Parallaxing 

### ISSUE THREAD

**Issue by JbrockPony** [IAMColumbia/NationalSpaceship#152]
### Description

The background moevement is too fast as player progresses. 
#### New Code

https://github.com/JbrockPony/2D-Platformer-V1/blob/master/Assets/Scripts/Parallaxing.cs
### Previous Work

N/A
### Other Notes

Help...

**Comment by noahmjohnson** [comment]
GitHub issues are meant to outline the requirments for the parts of your game, not the 'problems' with your game. Please reformat these issues to match the mechanics that your game requires.

If you need some guidance, look at how your peers are filing issues.
