### ISSUE TITLE
SC_Death/Respwan 

### ISSUE THREAD

**Issue by JbrockPony** [IAMColumbia/NationalSpaceship#153]
### Description

My player falls through the screen and does not respwan to my assigned respawn points. 
#### New Code

https://github.com/JbrockPony/2D-Platformer-V1/blob/master/Assets/Scripts/GameMaster.cs
### Previous Work

N/A
### Other Notes

N/A

**Comment by noahmjohnson** [comment]
Please see my comments in #152
