### ISSUE TITLE
SB_DoubleMoveBugFixed

### ISSUE THREAD

**Issue by TBGDeathPunch** [IAMColumbia/NationalSpaceship#154]
Description:
I was finally able to get my double movement bug fixed so that the player's character doesn't get trapped in a wall when he tries to move against it.

Requirements:
It was a very small change in the code and some double checking of the assets that the player was getting trapped in but now it works fine.

Link to code:
https://github.com/TBGDeathPunch/LizardLex/blob/master/Assets/Scripts/PlayerMove.cs

**Comment by noahmjohnson** [comment]
:+1:
