### ISSUE TITLE
SB_SecondLevel/SecondWhiteboxLevel

### ISSUE THREAD

**Issue by TBGDeathPunch** [IAMColumbia/NationalSpaceship#155]
Description:
This will be the base setup for the second level of the game. It will feature guards being setup in different ways from the first level and the player must use the new double move ability to get past each of the guard's vision without being seen and then make it to the levels exit. There will be another double movement ability orb in this level in case the player didn't get the first double movement ability orb that was in the first level. If the player is caught by one of the guards he or she will be forced to start from the beginning of the game without the double movement ability and will have to get it once again from the first level.

Requirements:
I will need to have enough different guards setup to force the player to use the double movement ability to get past them. A new double movement ability orb will need to be setup somewhere close to the start of the second level so that the player can use the ability to get past the guards. The double ability orb code will need to be changed a little bit from what it was to be able to check if the player already has the double movement ability or not. I will also need to make sure that when a guard catches the player the whole game is reset and the player is moved back to the beginning of the game without the double movement ability unlocked.

New Code:
There shouldn't really be any new code besides the new camera move when the player gets to the start of the new second level, which I will explain better in its own issue. I will edit the code of the double movement ability orb a little and I will make note of the change in its own issue or as an added comment to the earlier issue.

Previous Work:
Level 1:
https://github.com/TBGDeathPunch/LizardLex/blob/master/Assets/Levels/AllLevelsInOne.unity

Double Movement Ability Orb Script:
https://github.com/TBGDeathPunch/LizardLex/blob/master/Assets/Scripts/DoubleAbilityOrbScript.cs

Other Notes:
This may end up having a few bugs in it at first but all of the basic mechanics should be working by now in this level.

**Comment by TBGDeathPunch** [comment]
Link to Scene With New Level Added:
https://github.com/TBGDeathPunch/LizardLex/blob/master/Assets/Levels/AllLevelsInOne.unity

**Comment by noahmjohnson** [comment]
Excellent.

**Comment by TBGDeathPunch** [comment]
Thank you sir.
