### ISSUE TITLE
JB_fixingGroundBehavior

### ISSUE THREAD

**Issue by Shad0wKing92** [IAMColumbia/NationalSpaceship#164]
### Description

Right now there is a trigger box on the ground that when the player is in the box a bool is true, but once they jump the bool is false, and if the bool is false they can not jump again. Problem is that when there are multiple ground prefabs in the scene there are multiple instances of the bool making it true and false at the same time.
### Requirements

-Re-work the ground code to use events and event handlers
### Previous Work

https://github.com/Shad0wKing92/ColorTheory/blob/master/Assets/Scripts/GroundBehavior.cs
### Other Notes

this is the code as of now, I am probably going to make a groundManager that knows if it is on the ground, any ground, and if it isn't it wont be able to jump again.

**Comment by noahmjohnson** [comment]
:+1:
