### ISSUE TITLE
TF_EnemyDamage

### ISSUE THREAD

**Issue by Gamewiz21** [IAMColumbia/NationalSpaceship#183]
Description:
If the enemy touches the player he will take damage, likewise if the player gets too close to the enemy.

Requirements:
• If enemies touch the player his health goes down
• If player's health reaches zero the player will be killed

**Comment by Gamewiz21** [comment]
Enemy Damage Manager:
https://github.com/Gamewiz21/TM_-repository/blob/master/AESGame/Assets/EnemyScripts/Enemyhit.cs

**Comment by noahmjohnson** [comment]
Is the damage killing both enemies fixed?

**Comment by Gamewiz21** [comment]
Yes, I'll send the update
