### ISSUE TITLE
SH_Shader

### ISSUE THREAD

**Issue by saheinsen** [IAMColumbia/NationalSpaceship#193]
Background shader script that allows for a moving space background

**Comment by saheinsen** [comment]
https://github.com/saheinsen/Station_Resident_0/blob/master/Station%20Resident%200/Assets/scripts/Shader/scrollshaderwithcolorchange.shader

**Comment by noahmjohnson** [comment]
:+1:

**Comment by saheinsen** [comment]
Hey Noah, I got a question regarding events, do you have a few moments?

Stefan Heinsen
