### ISSUE TITLE
TF_Shader

### ISSUE THREAD

**Issue by Gamewiz21** [IAMColumbia/NationalSpaceship#207]
Description: 
The Plane will have a texture that moves to the right each frame and. you will be able to alter its color value.
Requirements;;
=>The object will move to the right
=>You will be ale to change its color value 

Other Notes:
This isn't  going to be apart of my game I just didn't know if we should have made an issue or not;
plus I needed to give you the link anyway.

**Comment by Gamewiz21** [comment]
https://github.com/Gamewiz21/TM_-repository/blob/master/AESGame/Assets/Textures/Clouds.shader

**Comment by noahmjohnson** [comment]
:+1:

**Comment by noahmjohnson** [comment]
https://guides.github.com/features/mastering-markdown/
