### ISSUE TITLE
CS_Shader

### ISSUE THREAD

**Issue by cbsstarks18** [IAMColumbia/NationalSpaceship#228]
Description 
Make the sprites repeat while camera moves left from right. Make clouds move in opposite direction.

https://github.com/cbsstarks18/Wu-Game/blob/master/SkyMover
https://github.com/cbsstarks18/Wu-Game/blob/master/CloudMover
https://github.com/cbsstarks18/Wu-Game/blob/master/Background

**Comment by noahmjohnson** [comment]
This was supposed to be implemented using the shader we wrote in class. Not in c#. Do you have the sample shader we wrote in class to base the functionality off of?
