### ISSUE TITLE
IH_Helmet and visor GUI

### ISSUE THREAD

**Issue by chocobo555** [IAMColumbia/NationalSpaceship#34]
# Working off of the work done in Metroid Prime I will simulate the experience of wearing a technologically advanced sci-fi flavored helmet.
### These interconnected systems are the crux of the game and as such of most importance. They can be considered completed when:
#1. The player feels a sense of presence within the helmet. It feels like they are wearing and looking out from a helmet.
#2. The physicality of the Rift and virtual helmet are close approximations of each other.
#3. The Visor must serve as basic GUI and as an extension of player intention. Its a tool that goes above and beyond what the player needs to know to play and goes into what the player needs to know to master. It should feel like a tool the main character created to help them navigate varied and difficult terrain.

**Comment by noahmjohnson** [comment]
@chocobo555 wrong format. Please name the issue properly and use the template set up here. https://github.com/IAMColumbia/NationalSpaceship/edit/master/issue_requirements.md

**Comment by noahmjohnson** [comment]
@chocobo555 please use the markup formatting found in the requirements above.

**Comment by noahmjohnson** [comment]
Where is the code for this issue?
