### ISSUE TITLE
IH_Oculus Rift Implementation

### ISSUE THREAD

**Issue by chocobo555** [IAMColumbia/NationalSpaceship#35]
# Get the Oculus Rift to function as the main camera in Unity. This will require that I use Oculus's Unity Integration and have it set up to head track accurately, minimize blur, and reach the highest resolution it is capable of.
### This will require time as the Integration, as well as the Oculus itself, are still in their prototype phases. I will know I have succeeded when I can reach the fidelity of general immersion that is present in Oculus Runtime's simple but effective calibration program. I will be using this as a benchmark that shows the Oculus when implemented correctly.

https://github.com/chocobo555/PRiME/blob/de3a8307d6e4aa0916bb3518930dbd8b9948bfeb/Assets/Scripts/TurnWithRift2.cs

**Comment by noahmjohnson** [comment]
@chocobo555 wrong format. Please name the issue properly and use the template set up here. https://github.com/IAMColumbia/NationalSpaceship/edit/master/issue_requirements.md

**Comment by noahmjohnson** [comment]
Where is the code for this issue?
