### ISSUE TITLE
IH_Movement

### ISSUE THREAD

**Issue by chocobo555** [IAMColumbia/NationalSpaceship#36]
# Once the Oculus Implementation is done this mechanic can begin to be coded.
### Additionally just like jumping the ground movement will have to feel good on the Oculus Rift without causing discomfort for the player. The jump is a source of agency for the player.

https://github.com/chocobo555/PRiME/blob/172fd6546e4374865bee5d57e37adb04d1f5feec/Assets/Scripts/Movement.cs

**Comment by noahmjohnson** [comment]
@chocobo555 wrong format. Please name the issue properly and use the template set up here. https://github.com/IAMColumbia/NationalSpaceship/edit/master/issue_requirements.md

**Comment by noahmjohnson** [comment]
Where is the code for this issue?
