### ISSUE TITLE
IH_JumpMechanic

### ISSUE THREAD

**Issue by chocobo555** [IAMColumbia/NationalSpaceship#37]
# Right now, before the jump can enter an initial prototype phase, the Oculus Rift implementation needs to be mostly or completely done. The helmet GUI will also have to be at least be in a prototype phase as the jump and the GUI work in tandem.
### Creation of a jump mechanic. The jump should be agile to boost the players sense of agency in regards to the Power Suit. This means that it needs to have a good sense of acceleration and momentum, enough height to feel like the player doesn't jump so much as leap, and good horizontal distance both for the increased agency and for moving around the environment. The physics involved in all of this will need to be iterated upon multiple times. Adjusting a few values even a little will result in a leap with a very different feel. The goal is to have both a leap that is effective at navigating the environment and give the player a sense of being powerful and skillful while they  are doing it.

https://github.com/chocobo555/PRiME/blob/172fd6546e4374865bee5d57e37adb04d1f5feec/Assets/Scripts/Movement.cs

**Comment by noahmjohnson** [comment]
@chocobo555 wrong format. Please name the issue properly and use the template set up here. https://github.com/IAMColumbia/NationalSpaceship/edit/master/issue_requirements.md

**Comment by noahmjohnson** [comment]
Where is the code for this issue?

**Comment by chocobo555** [comment]
I have code for this but I'm in the process of moving so I'm not near a
computer.
