### ISSUE TITLE
JB_Movement

### ISSUE THREAD

**Issue by Shad0wKing92** [IAMColumbia/NationalSpaceship#38]
### Description

Basic Movement Code for the player. Left and Right movement, Jumping, and Grabbing.
### Requirements

Player must move side to side and slow down with the drag,
-the player can not jump if in air,
-the player has to be able to grab and object and have it follow, then be able to drop an object.
#### New Code

https://github.com/Shad0wKing92/ColorTheory/blob/master/Assets/Scripts/MovementScript.cs
### Previous Work

up to date
### Other Notes

no notes

**Comment by noahmjohnson** [comment]
Looks good to me (lgtm)
For the requirements, maybe create a bullet point list to help visualize all of the requirements.
- Player must move side to side and slow down with the drag
- the player can not jump if in air
-  the player has to be able to grab and object and have it follow, then be able to drop an object
