### ISSUE TITLE
IH_Scanning Mechanic

### ISSUE THREAD

**Issue by chocobo555** [IAMColumbia/NationalSpaceship#48]
By looking directly at specific points in the environment while holding down a specified button the player will be able to lock-on and gain information about the object. A Raycast set at the midpoint of the two Oculus cameras will create a focal point for the players gaze such that if they are staring directly at something of interest they can hold down the Scan button and the visor will bring up information that pertains to the environment they are exploring. Only certain key items are scannable. Similar to a collectathon, which is common in 3d platformers, the player's goal is to find and scan all points of interest which will yield the information they came to the the planet to collect. This gives the player  a set goal that will bring them through multiple platforming challenges. The location of these points will be known to the player only in broad locations, encouraging the player to explore and platform.

**Comment by noahmjohnson** [comment]
Where is the code for this issue?
