### ISSUE TITLE
IH_Advanced Traversal Ability

### ISSUE THREAD

**Issue by chocobo555** [IAMColumbia/NationalSpaceship#49]
# This mechanic I am framing as an addition if everything else gets done or if I decide it is necessary to make the game interesting.

**Comment by noahmjohnson** [comment]
@chocobo555 wrong format. Please name the issue properly and use the template set up here. https://github.com/IAMColumbia/NationalSpaceship/edit/master/issue_requirements.md

**Comment by noahmjohnson** [comment]
Where is the code for this issue?
