### ISSUE TITLE
TF_Item Collection

### ISSUE THREAD

**Issue by Gamewiz21** [IAMColumbia/NationalSpaceship#62]
Description
The player will have collectibles that the player will be able to collect. The player will be collecting small crystals that will be indicted on the HUD by the amount the player has collected and will increment its value with each crystal the player comes in contact with.

Requirements
• Player will be able come into contact with the crystal
• The crystal will disappear from view
• The crystal will add to the player’s current amount 
• The value will be shown as a GUI on the player HUD

**Comment by Gamewiz21** [comment]
// Collect crystals
https://github.com/Gamewiz21/TM_-repository/blob/master/AESGame/Assets/MyScripts/CrystalGet.cs
//Crystal manager
https://github.com/Gamewiz21/TM_-repository/blob/master/AESGame/Assets/MyScripts/CountingCrystal.cs

**Comment by noahmjohnson** [comment]
This is not functioning properly. Can I get an update?

**Comment by Gamewiz21** [comment]
I don't  know why  item collection  has always worked

**Comment by Gamewiz21** [comment]
GitHub is conflicting when I try to update this, I can get it working on my end but for some reason I keep getting conflicted and it adds some comments on my code for some reason; I added code for sound effects.
https://github.com/Gamewiz21/TM_-repository/blob/master/AESGame/Assets/MyScripts/CrystalGet.cs

**Comment by Gamewiz21** [comment]
Updated CrystalGet:
https://github.com/Gamewiz21/TF_GAIA/blob/master/AESGame/Assets/MyScripts/CrystalGet.cs
