### ISSUE TITLE
MG_PlayerShoot

### ISSUE THREAD

**Issue by marco1251** [IAMColumbia/NationalSpaceship#71]
Description
The player will be able to shoot in four directions (up, down, left ,right) using the arrow keys.

requirements
-character will shoot bullets either up, down, left, or right based on what arrow key is pressed
-character can only shoot in one direction (can't shoot in multiple direction at the same time)
-bullets will be a trigger that take effect when going through an enemy
-bullets will disappear 5 seconds after being shot by player

New Code

Player Shoot code
https://github.com/marco1251/MG_MusicShooter/blob/master/MusicShooter/Assets/Scripts/PlayerShoot.cs

Destroys bullet  https://github.com/marco1251/MG_MusicShooter/blob/master/MusicShooter/Assets/Scripts/BulletDestroy.cs

Previous Work
none

Other Notes
Made it so that player can only shoot in one direction at a time. Also made it so that bullets disappear from the scene two seconds after being fired. Bullets no longer collide against each other.

**Comment by noahmjohnson** [comment]
@marco1251 wrong format. Please name the issue properly and use the template set up here. https://github.com/IAMColumbia/NationalSpaceship/edit/master/issue_requirements.md
