### ISSUE TITLE
MG_EnemyMovement

### ISSUE THREAD

**Issue by marco1251** [IAMColumbia/NationalSpaceship#72]
Description
Enemies will move around the screen. They will not actively target the player but they will move in a general direction past the center of the screen.

Requirements
-Instantiate function will spawn enemies every couple of seconds
-enemies will start to head towards the center of the screen or move straight across the screen from where they spawn
-enemies will only move forward, they will not change direction
-some enemies will move faster than others

New Code 
none

Previous Work
none

Other Notes

**Comment by noahmjohnson** [comment]
@marco1251 wrong format. Please name the issue properly and use the template set up here. https://github.com/IAMColumbia/NationalSpaceship/edit/master/issue_requirements.md

**Comment by marco1251** [comment]
enemy state script
https://github.com/marco1251/MG_MusicShooter/blob/master/MusicShooter/Assets/Scripts/Enemy.cs

Enemies currently follow the player.
