### ISSUE TITLE
MG_LevelMusic

### ISSUE THREAD

**Issue by marco1251** [IAMColumbia/NationalSpaceship#73]
Description
music will start at the beginning of the level and will indicate level completion when it ends. 

Requirements
-the music will start and enemies will start spawning at the beginning of the level
-music will end to indicate the end of the level 
-enemies will stop spawning and the level will end/restart/next level
-there is an indicator on the screen that tells the player how far along in the song/level they are

New Code
none

Previous Work
none

Other Notes

**Comment by noahmjohnson** [comment]
@marco1251 wrong format. Please name the issue properly and use the template set up here. https://github.com/IAMColumbia/NationalSpaceship/edit/master/issue_requirements.md
