### ISSUE TITLE
MG_EnemyDeath

### ISSUE THREAD

**Issue by marco1251** [IAMColumbia/NationalSpaceship#74]
Description
the enemies will play sounds when they are destroyed by the player 

Requirements
-enemies will be destroyed when touched by a player bullet
-player bullets are triggers that will be deactivated when they touch an enemy
-when destroyed, an enemy will be removed from the game and a sound will play (both enemy and bullet will disappear from the game)
-some enemies will explode into smaller enemies that can hurt the player on contact 

New Code

void OnTriggerEnter(Collider other)
    {

```
    if (other.gameObject.tag == ("PlayerBullet"))
    {
     Destroy(this.gameObject);
     print("enemy hit");
    }

    if (other.gameObject.tag == ("Player"))
    {
        print("player has been hit");
    }

}
```

Previous Work
none

Other Notes
I want to have my player bullets destroying enemies as my first encounter/whitebox assignment for class 4 (2/17/15)

**Comment by noahmjohnson** [comment]
@marco1251 wrong format. Please name the issue properly and use the template set up here. https://github.com/IAMColumbia/NationalSpaceship/edit/master/issue_requirements.md

**Comment by marco1251** [comment]
enemy state script
https://github.com/marco1251/MG_MusicShooter/blob/master/MusicShooter/Assets/Scripts/Enemy.cs

Enemies lose health when hit by a player bullet. Enemies get destroyed when health reaches 0.
