### ISSUE TITLE
MG_PlayerDeath

### ISSUE THREAD

**Issue by marco1251** [IAMColumbia/NationalSpaceship#75]
Description 
player will lose a life when touched by an enemy. level will reset when player is out of lives.

Requirements
-the player will have 3 lives (health)
-touching an enemy will cause the player to lose a life
-when touched by an enemy, the player will respawn at the center of the level and lose a life
-the player will have a couple of seconds of invincibility at each spawn
-during invincibility the player can go through enemies and will not take any damage
-once the player runs out of lives, the level will indicate failure and restart  

New Code
none

Previous Work
none

Other Notes

**Comment by noahmjohnson** [comment]
@marco1251 wrong format. Please name the issue properly and use the template set up here. https://github.com/IAMColumbia/NationalSpaceship/edit/master/issue_requirements.md

**Comment by marco1251** [comment]
https://github.com/marco1251/MG_MusicShooter/blob/master/MusicShooter/Assets/Scripts/Player/PlayerDeath.cs
