### ISSUE TITLE
CM_PlayerMovement

### ISSUE THREAD

**Issue by coryMedrano1** [IAMColumbia/NationalSpaceship#76]
### Description

This will allow the player to move around in the level. Since this is in 2D the player will only need to move left and right.
### Requirements

When the "a" key is pressed, the character should move left at a certain speed.
When the "d" key is pressed, the character should move right at a certain speed.
#### New Code

https://github.com/coryMedrano1/EcoTGM/blob/master/Eco/Assets/scripts/characterControllerScript.cs
### Previous Work

None

**Comment by noahmjohnson** [comment]
This looks to be one day late.

**Comment by noahmjohnson** [comment]
My mistake, disregard last comment.

**Comment by coryMedrano1** [comment]
New Code: https://github.com/coryMedrano1/EcoTGM/blob/master/Eco/Assets/scripts/characterControllerScript.cs
