### ISSUE TITLE
CM_PlayerJumping

### ISSUE THREAD

**Issue by coryMedrano1** [IAMColumbia/NationalSpaceship#77]
### Description

This allows the player to jump. Is used for platforming, dodging, and can also be combined with attacks.
### Requirements

When the "w" key is pressed, character should jump up to a certain height and then fall back down.
#### New Code

https://github.com/coryMedrano1/EcoTGM/blob/master/Eco/Assets/scripts/characterControllerScript.cs
### Previous Work

None

**Comment by noahmjohnson** [comment]
This looks to be one day late.

**Comment by coryMedrano1** [comment]
New Code: https://github.com/coryMedrano1/EcoTGM/blob/master/Eco/Assets/scripts/characterControllerScript.cs
