### ISSUE TITLE
CM_PlayerAttack

### ISSUE THREAD

**Issue by coryMedrano1** [IAMColumbia/NationalSpaceship#78]
### Description

Allows player to attack. Attacks can be used to defeat enemies. For right now, only need a forward attack that will allow the player to attack left and right.
### Requirements

When "left arrow" key is pressed, character should attack to the left.
When "right arrow" key is pressed, character should attack to the right.
If enemy is in range of attack, enemy should take a certain amount of damage.
#### New Code

https://github.com/coryMedrano1/EcoTGM/blob/master/Eco/Assets/scripts/attackScript.cs
### Previous Work

None

**Comment by noahmjohnson** [comment]
This looks to be one day late.

**Comment by coryMedrano1** [comment]
New Code: https://github.com/coryMedrano1/EcoTGM/blob/master/Eco/Assets/scripts/attackScript.cs

**Comment by noahmjohnson** [comment]
Please comment this code.
