### ISSUE TITLE
CM_EnemyMovement

### ISSUE THREAD

**Issue by coryMedrano1** [IAMColumbia/NationalSpaceship#79]
### Description

Enemy will move towards the player in order to attack.
### Requirements

Enemy should move toward the player in order to get into a certain position to the player.
#### New Code

https://github.com/coryMedrano1/EcoTGM/blob/master/Eco/Assets/scripts/enemyAIScript.cs
### Previous Work

None

**Comment by noahmjohnson** [comment]
This looks to be one day late.

**Comment by coryMedrano1** [comment]
New Code: https://github.com/coryMedrano1/EcoTGM/blob/master/Eco/Assets/scripts/enemyAIScript.cs
