### ISSUE TITLE
CM_EnemyAttack

### ISSUE THREAD

**Issue by coryMedrano1** [IAMColumbia/NationalSpaceship#80]
### Description

Enemy will attack player once close enough to attack and do damage.
### Requirements

When enemy is in a certain position to the player, enemy should attack.
If player is in range of attack, player should take certain amount of damage.
#### New Code

None
### Previous Work

None

**Comment by noahmjohnson** [comment]
This looks to be one day late.

**Comment by coryMedrano1** [comment]
https://github.com/coryMedrano1/EcoTGM/blob/master/Eco/Assets/scripts/enemyAttackScript.cs
