### ISSUE TITLE
CM_PlayerHealth

### ISSUE THREAD

**Issue by coryMedrano1** [IAMColumbia/NationalSpaceship#82]
### Description

The players health will be displayed in the to left corner of the screen.This will keep track of how much health the player currently has. Will decrease when damaged and increase when health is picked up.
### Requirements

Should display at top left of screen.
Should decrease by a certain amount when hit by enemy attack.
Should increase by a certain amount when player get health pick up.
#### New Code

None
### Previous Work

None

**Comment by noahmjohnson** [comment]
Is this an issue that outlines the mechanics for your week 2 homework?

**Comment by coryMedrano1** [comment]
https://github.com/coryMedrano1/EcoTGM/blob/master/Eco/Assets/scripts/UIControlScript.cs
